OwinAuth/Models/Annoucement.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace OwinAuth.Models
{
    public class Annoucement
    {
        [Key]
        public Guid Id { get; set; }
        [MaxLength(50)]
        public string Title { get; set; }
        [MaxLength(500)]
        public string Details { get; set; }
        public byte[] Image { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public bool IsPopup { get; set; }
        public bool IsPublished { get; set; }
        public int Priority { get; set; }
        public DateTime CreatedDateTime { get; set; }
    }
}

OwinAuth/Controllers/AnnoucementsController.cs
using System;
using System.Data;
using PagedList;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OwinAuth.DAL;
using OwinAuth.Models;
using System.IO;
using System.Threading.Tasks;
using OwinAuth.Utils;
using OwinAuth.AuthAttribute;
using OwinAuth.ViewModels;

namespace OwinAuth.Controllers
{
    public class AnnoucementsController : Controller
    {
        private SchoolContext db = new SchoolContext();
        [Authorize(Roles = "Admin, Member")]
        public ActionResult Index(string sortOrder, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CreatedDateSortParm = string.IsNullOrEmpty(sortOrder) ? "CreatedDate_desc" : "";
            ViewBag.TitleSortParm = sortOrder == "Title_asc" ? "Title_desc" : "Title_asc";
            ViewBag.PublishedDateSortParm = sortOrder == "StartDate_asc" ? "StartDate_desc" : "StartDate_asc";
            ViewBag.ExpiredDateSortParm = sortOrder == "EndDate_asc" ? "EndDate_desc" : "EndDate_asc";
            ViewBag.OrderSortParm = sortOrder == "Order_asc" ? "Order_desc" : "Order_asc";

            var annoucements = from s in db.Annoucements
                               select new AnnouncementViewModel {
                                   Id = s.Id,
                                   Title = s.Title,
                                   Details = s.Details,
                                   StartDate = s.StartDate,
                                   EndDate = s.EndDate,
                                   Priority = s.Priority,
                                   IsPopup = s.IsPopup,
                                   IsPublished = s.IsPublished,
                                   CreatedDateTime = s.CreatedDateTime
                               };
            switch (sortOrder)
            {
                case "CreatedDate_asc":
                    annoucements = annoucements.OrderBy(s => s.CreatedDateTime);
                    break;
                case "Title_desc":
                    annoucements = annoucements.OrderByDescending(s => s.Title);
                    break;
                case "Title_asc":
                    annoucements = annoucements.OrderBy(s => s.Title);
                    break;
                case "StartDate_desc":
                    annoucements = annoucements.OrderByDescending(s => s.StartDate);
                    break;
                case "StartDate_asc":
                    annoucements = annoucements.OrderBy(s => s.StartDate);
                    break;
                case "EndDate_desc":
                    annoucements = annoucements.OrderByDescending(s => s.EndDate);
                    break;
                case "EndDate_asc":
                    annoucements = annoucements.OrderBy(s => s.EndDate);
                    break;
                case "Order_asc":
                    annoucements = annoucements.OrderBy(s => s.Priority);
                    break;
                case "Order_desc":
                    annoucements = annoucements.OrderByDescending(s => s.Priority);
                    break;
                default:
                    annoucements = annoucements.OrderByDescending(s => s.CreatedDateTime);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(annoucements.ToPagedList(pageNumber, pageSize));
        }
        public async Task<ActionResult> RenderImage(int id)
        {
            Annoucement item = await db.Annoucements.FindAsync(id);

            byte[] photoBack = item.Image;

            return File(photoBack, "image/png");
        }

        [Authorize(Roles = "Member")]
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Annoucement annoucement = db.Annoucements.Find(id);
            if (annoucement == null)
            {
                return HttpNotFound();
            }
            AnnouncementViewModel viewmodel = new AnnouncementViewModel();
            viewmodel.Id = annoucement.Id;
            viewmodel.Title = annoucement.Title;
            viewmodel.Details = annoucement.Details;
            viewmodel.StartDate = annoucement.StartDate;
            viewmodel.EndDate = annoucement.EndDate;
            viewmodel.CreatedDateTime = annoucement.CreatedDateTime;
            viewmodel.IsPopup = annoucement.IsPopup;
            viewmodel.Image = annoucement.Image;
            viewmodel.IsPublished = annoucement.IsPublished;
            viewmodel.Priority = annoucement.Priority;
            return View(viewmodel);
        }

        [Authorize]
        public ActionResult Create()
        {
            AnnouncementViewModel item = new AnnouncementViewModel();
            item.StartDate = DateTime.Now;
            item.EndDate = DateTime.Now;
            return View(item);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create(AnnouncementViewModel viewmodel)
        {
            HttpPostedFileBase file = viewmodel.ImageStore;
            dynamic showMessageString = string.Empty;
            if (ModelState.IsValid && file != null)
            {
                if (file != null && file.FileName != null && file.FileName != "")
                {
                    var fileExtension = new string[] { "jpeg", "jpg", "png", "gif", "bmp", ".jpeg", ".jpg", ".png", ".gif", ".bmp" };
                    FileInfo fi = new FileInfo(file.FileName);
                    if (fileExtension.Contains(fi.Extension.ToLower()))
                    {
                        var announcementEntity = new Annoucement();
                        announcementEntity.Title = viewmodel.Title;
                        announcementEntity.Details = viewmodel.Details;
                        announcementEntity.StartDate = viewmodel.StartDate;
                        announcementEntity.EndDate = viewmodel.EndDate;
                        announcementEntity.IsPopup = viewmodel.IsPopup;
                        announcementEntity.Priority = viewmodel.Priority;
                        announcementEntity.Image = FileHelper.ConvertToBytes(file);
                        announcementEntity.CreatedDateTime = DateTime.Now;
                        announcementEntity.Id = Guid.NewGuid();
                        
                        try
                        {
                            db.Annoucements.Add(announcementEntity);
                            db.SaveChanges();
                            showMessageString = new
                            {
                                param1 = 200,
                                param2 = "Insert data successfully !!!"
                            };
                        }
                        catch (Exception)
                        {
                            showMessageString = new
                            {
                                param1 = 404,
                                param2 = "Exception occured while insert database"
                            };
                        }
                    }
                }
            }
            else
            {
                showMessageString = new
                {
                    param1 = 404,
                    param2 = "Input data is not valid!"
                };
            }
            return Json(showMessageString, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Annoucement annoucement = db.Annoucements.Find(id);
            if (annoucement == null)
            {
                return HttpNotFound();
            }
            AnnouncementViewModel viewmodel = new AnnouncementViewModel();
            viewmodel.Id = annoucement.Id;
            viewmodel.Title = annoucement.Title;
            viewmodel.Details = annoucement.Details;
            viewmodel.StartDate = annoucement.StartDate;
            viewmodel.EndDate = annoucement.EndDate;
            viewmodel.CreatedDateTime = annoucement.CreatedDateTime;
            viewmodel.IsPopup = annoucement.IsPopup;
            viewmodel.IsPublished = annoucement.IsPublished;
            viewmodel.Image = annoucement.Image;
            viewmodel.Priority = annoucement.Priority;
            return View(viewmodel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "Id,Title,Details,Image,StartDate,EndDate,IsPopup,Priority")] AnnouncementViewModel annoucement)
        {
            if (ModelState.IsValid)
            {
                var annoucementForEdit = db.Annoucements.Where(x => x.Id == annoucement.Id).Single();
                annoucementForEdit.Title = annoucement.Title;
                annoucementForEdit.Details = annoucement.Details;
                annoucementForEdit.StartDate = annoucement.StartDate;
                annoucementForEdit.EndDate = annoucement.EndDate;
                annoucementForEdit.IsPopup = annoucement.IsPopup;
                annoucementForEdit.Priority = annoucement.Priority;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(annoucement);
        }

        [Authorize]
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Annoucement annoucement = db.Annoucements.Find(id);
            if (annoucement == null)
            {
                return HttpNotFound();
            }
            AnnouncementViewModel viewmodel = new AnnouncementViewModel();

OwinAuth/Views/Annoucements/Create.cshtml
@model OwinAuth.ViewModels.AnnouncementViewModel
@using OwinAuth.Utils;
@{
    ViewBag.Title = "Create";
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script type="text/javascript">
    function fileCheck(obj) {
        var fileExtension = ['jpeg', 'jpg', 'png', 'gif', 'bmp'];
        if ($.inArray($(obj).val().split('.').pop().toLowerCase(), fileExtension) == -1) {
            alert("Only '.jpeg','.jpg', '.png', '.gif', '.bmp' formats are allowed.");
            $(obj).val("");
        }
    }
    $(document).ready(function(){
        $("textarea").keyup(function(){
            var max = 500;
            var remind = max - $("#Details").val().length;
            $("#remind").text("Max 500 chars,. Remaining "+remind+" char(s)");
        });
    });
    function onSuccess(response) {
        if (response.param1 == 200) {
            window.location.href = '@Url.Action("Index", "Annoucements")';
        }
    }
    function OnFailure(response) {
        alert('HTTP Status Code: ' + response.param1 + '  Error Message: ' + response.param2);
    }
</script>

@using (Ajax.BeginForm("Create", "Annoucements", new AjaxOptions { HttpMethod = "POST", OnSuccess = "onSuccess", OnFailure = "OnFailure" }, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger"})
        <div class="form-group">
            @Html.LabelFor(model => model.Title, UI.AnnouncementTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Details, UI.AnnouncementDetails, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Details, new { htmlAttributes = new { } })
                @Html.ValidationMessageFor(model => model.Details, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <span class="col-md-2"></span>
            <div class="col-md-10">
                <span id="remind">Max 500 chars,. Remaining 200 char(s)</span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, UI.PublishedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, UI.ExpiryDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.ImageStore, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(m => m.ImageStore, new { @class = "form-control", type = "file" })
                @Html.ValidationMessageFor(m => m.ImageStore)
            </div>
        </div>   

        <div class="form-group">
            @Html.LabelFor(model => model.IsPopup, UI.ShowAsPopup, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsPopup)
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Priority, UI.Order, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Priority, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Cancel" class="btn btn-default" onclick="location.href='@Url.Action("Index","Annoucements")';" />
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <span id="message"></span>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

OwinAuth/Views/Annoucements/Delete.cshtml
@model OwinAuth.ViewModels.AnnouncementViewModel
@using OwinAuth.Utils;
@{
    ViewBag.Title = "Delete";
}
<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, UI.AnnouncementTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Details, UI.AnnouncementDetails, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Details, new { @disabled = "disabled" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="data:image;base64,@System.Convert.ToBase64String(Model.Image)" width="160" height="160" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, UI.PublishedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, "{0:MM/dd/yyyy}", new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, UI.ExpiryDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, "{0:MM/dd/yyyy}", new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsPopup, UI.ShowAsPopup, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsPopup, new { htmlAttributes = new { @disabled = "disabled" } })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Priority, UI.Order, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Priority, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>
        </div>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

OwinAuth/Views/Annoucements/Details.cshtml
@model OwinAuth.ViewModels.AnnouncementViewModel
@using OwinAuth.Utils;
@{
    ViewBag.Title = "Details";
}
<div>
    <hr />
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, UI.AnnouncementTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Details, UI.AnnouncementDetails, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Details, new { @disabled = "disabled" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="data:image;base64,@System.Convert.ToBase64String(Model.Image)" width="160" height="160" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, UI.PublishedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, "{0:MM/dd/yyyy}", new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, UI.ExpiryDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, "{0:MM/dd/yyyy}", new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsPopup, UI.ShowAsPopup, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsPopup, new { htmlAttributes = new { @disabled = "disabled" } })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Priority, UI.Order, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Priority, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>
        </div>
    </div>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

OwinAuth/Views/Annoucements/Edit.cshtml
@model OwinAuth.ViewModels.AnnouncementViewModel
@using OwinAuth.Utils;
@{
    ViewBag.Title = "Edit";
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript">
    function fileCheck(obj) {
        var fileExtension = ['jpeg', 'jpg', 'png', 'gif', 'bmp'];
        if ($.inArray($(obj).val().split('.').pop().toLowerCase(), fileExtension) == -1) {
            alert("Only '.jpeg','.jpg', '.png', '.gif', '.bmp' formats are allowed.");
        }
    }
    $(document).ready(function () {
        var max = 500;
        var remind = max - $("#Details").val().length;
        $("#remind").text("Max 500 chars,. Remaining " + remind + " char(s)");
        $("textarea").keyup(function () {
            var max = 500;
            var remind = max - $("#Details").val().length;
            $("#remind").text("Max 500 chars,. Remaining " + remind + " char(s)");
        });
    });
</script>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, UI.AnnouncementTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Details, UI.AnnouncementDetails, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Details, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Details, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <span class="col-md-2"></span>
            <div class="col-md-10">
                <span id="remind">Max 500 chars,. Remaining 200 char(s)</span>
            </div>
        </div>
        @*<div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageData" id="ImageData" onchange="fileCheck(this);" />
            </div>
        </div>*@
        <div class="form-group">
            @Html.LabelFor(m => m.ImageStore, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">
                @Html.TextBoxFor(m => m.ImageStore, new { @class = "form-control", type = "file" })
                @Html.ValidationMessageFor(m => m.ImageStore)
            </div>
        </div>   

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, UI.PublishedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, "{0:MM/dd/yyyy}", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, UI.ExpiryDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, "{0:MM/dd/yyyy}", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsPopup, UI.ShowAsPopup, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsPopup)
                    @Html.ValidationMessageFor(model => model.IsPopup, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Priority, UI.Order, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Priority, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OwinAuth/Views/Annoucements/Index.cshtml
@model PagedList.IPagedList<OwinAuth.ViewModels.AnnouncementViewModel>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
@{
    ViewBag.Title = "Index";
}
<script type="text/javascript">
    $(document).ready(function(){
        var total = @Model.TotalItemCount;
        var pageSize = @Model.PageSize;//10
        var pageCount = @Model.PageCount;//2
        var pageNumber = @Model.PageNumber;//1
        var temp = (pageNumber - 1) * pageSize;
        var before = 0;
        if(pageNumber == 1){
            before = 1;
        }else{
            before = temp + 1;
        }
        var after = pageSize * pageNumber;
        var remind = 0;
        if(pageCount == pageNumber){
            remind = total - temp;
            after = temp + remind;
        }
        $("#pageinfor").text(before +" - "+ after + " of "+ total + " records");
    });

</script>
<p id="pageinfor">
</p>
<table class="table  table-bordered">
    <tr>
        <th>
            @Html.ActionLink("Created Date", "Index", new { sortOrder = ViewBag.CreatedDateSortParm })
        </th>
        <th>
            @Html.ActionLink("Annoucement Title", "Index", new { sortOrder = ViewBag.TitleSortParm })
        </th>
        <th>
            @Html.ActionLink("Published Date", "Index", new { sortOrder = ViewBag.PublishedDateSortParm })
        </th>
        <th>
            @Html.ActionLink("Expired Date", "Index", new { sortOrder = ViewBag.ExpiredDateSortParm })
        </th>
        <th>
            @Html.ActionLink("Order", "Index", new { sortOrder = ViewBag.OrderSortParm })
        </th>
        <th>
            @Html.Label("Action", new { id = "action" })
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Priority)
            </td>
            <td>
                @Html.ActionLink("View", "Details", new { id = item.Id })
                @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }), PagedListRenderOptions.ClassicPlusFirstAndLast)